
def generate_blank_record():

    record = {
        "processed": None,
        "who_id": None,
        "dataset": None,
        "prop_id": None,
        "keep": None,
        "duplicate_record_id": None,
        "who_region": None,
        "country_territory_area": None,
        "iso": None,
        "iso_3166_1_numeric": None,
        "admin_level": None,
        "area_covered": None,
        "prov_category": None,
        "prov_subcategory": None,
        "prov_measure": None,
        "who_code": None,
        "who_category": None,
        "who_subcategory": None,
        "who_measure": None,
        "comments": None,
        "date_start": None,
        "measure_stage": None,
        "prev_measure_number": None,
        "following_measure_number": None,
        "date_end": None,
        "reason_ended": None,
        "targeted": None,
        "enforcement": None,
        "non_compliance_penalty": None,
        "value_usd": None,
        "percent_interest": None,
        "date_entry": None,
        "link": None,
        "link_live": None,
        "link_eng": None,
        "source": None,
        "source_type": None,
        "alt_link": None,
        "alt_link_live": None,
        "alt_link_eng": None,
        "source_alt": None,
        "queries_comments": None,
    }

    return record
